### ISSUE TITLE
Composer.json is valid but composer.lock has some errors

### ISSUE THREAD

**Issue by AkechiShiro** [Seldaek/phar-utils#8]
Hi,

Is there any way to fix this issue ? 
```
./seld/phar-utils/1.2.1/composer.json is valid but your composer.lock has some errors
# Lock file errors
- The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
```
I'm willing to work on a pull request.

```bash
/tmp/nix-b/source/repository/seld/phar-utils/1.2.1 ❯ composer upgrade
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
No installed packages - skipping audit.
/tmp/nix-b/source/repository/seld/phar-utils/1.2.1 ❯ composer upgrade --lock
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
No installed packages - skipping audit.
```

**Comment by Seldaek** [comment]
Well, I am not sure what you are saying here.. Do you still see this issue even after doing `composer update --lock`? If so I'd really appreciate a copy of the composer.json and composer.lock that trigger this.

**Comment by Seldaek** [comment]
Sorry, didn't realize which repo I was on here. Hopefully it's fixed for you too now.

**Comment by AkechiShiro** [comment]
- `Composer.lock` : https://github.com/passbolt/passbolt_api/blob/master/composer.lock
- `Composer.json` : https://github.com/passbolt/passbolt_api/blob/master/composer.json
These 2 files still trigger this error after a `composer update --lock`

**Comment by AkechiShiro** [comment]
@Seldaek it is not fixed on my end, sadly, could you please take a look ?

**Comment by AkechiShiro** [comment]
@dlen @ishanvyas22 any idea what could be the issue here as it is linked to Passbolt ?

**Comment by AkechiShiro** [comment]
Ah sorry for pinging everyone, I did not see the last commit @Seldaek made, this issue should be resolved since last week.

I will attempt to do some testing and report.
